name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm install
        run: |
          npm install
          npm ci
      - name: npm build
        run: |
          npm run build
          cp README.md ./dist/README.MD
          cp CHANGELOG ./dist/CHANGELOG

      - name: publish
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com:websxz/zykj.git
          BRANCH: main
          FOLDER: dist
          SSH_PRIVATE_KEY: ${{ secrets.sshkey }}